### ISSUE TITLE
Create reference insert operation

### ISSUE THREAD

**Issue by kloppstock** [kloppstock/tree_data_structure#1]
Implement a reference insert function, which contains the balance.

**Comment by de-narm** [comment]
After I got both delete-examples from the course to work, I wanted to test something more extreme, unfortunately the insert function went all over the place.
I've used:

```
insert(30);
insert(38);
insert(42);
insert(10);
insert(20);
insert(25);
insert(32);
insert(34);
insert(40);
insert(41);
insert(44);
insert(11);
insert(80);
insert(66);
insert(55);
insert(2);
insert(6);
insert(7);
insert(50);
insert(56);
save_btree("test.svg", root);
```

Which resultet in [this](http://i.imgur.com/U5fcrvR.png).

**Comment by matzeni07** [comment]
I think looks good now.

![tree](https://cloud.githubusercontent.com/assets/15114116/20272638/d14dad3a-aa8e-11e6-9bf5-45d6dea032e0.png)
