### ISSUE TITLE
Knoten werden beim splitten nicht richtig initialisiert

### ISSUE THREAD

**Issue by arbu** [kloppstock/tree_data_structure#8]
wenn beim Einfügen in einen vollen Knoten ein neuer Knoten alloziert wird, werden die letzen beiden Werte in children nicht gesetzt, was dazu führt, dass da random Werte drin stehen. Wenn dann noch ein Wert in den Knoten eingefügt und so die Anzahl der möglichen Kindknoten erhöht wird, funktioniert get_btree_depth nicht mehr.
Mein Vorschlag wäre in insert.c alle malloc durch calloc zu ersetzen, oder beim erstellen eines Knoten alle Kinder auf 0 zu setzen.

**Comment by matzeni07** [comment]
erledigt
